const FIVE_MINUTES_IN_SECONDS = 5 * 60;
const SIXTY_MINUTES_IN_SECONDS = 60 * 60;
const TWO_HOURS_IN_SECONDS = 2 * 60 * 60;
const THIRTY_DAYS_IN_SECONDS = 30 * 24 * 60 * 60;

module.exports = {
  FIVE_MINUTES_IN_SECONDS,
  SIXTY_MINUTES_IN_SECONDS,
  TWO_HOURS_IN_SECONDS,
  THIRTY_DAYS_IN_SECONDS
};
